#pragma once

#define WIN32_LEAN_AND_MEAN
#include <windows.h>

#define VK_NO_PROTOTYPES
#include "vulkan-headers/vulkan.h"
#include "vulkan-headers/vulkan_win32.h"

// Global DLL handle and core function pointers
extern HMODULE g_vkModule;
extern PFN_vkGetInstanceProcAddr pfn_vkGetInstanceProcAddr;
extern PFN_vkGetDeviceProcAddr pfn_vkGetDeviceProcAddr;

// Instance-level
extern PFN_vkCreateInstance pfn_vkCreateInstance;
extern PFN_vkDestroyInstance pfn_vkDestroyInstance;
extern PFN_vkEnumeratePhysicalDevices pfn_vkEnumeratePhysicalDevices;
extern PFN_vkGetPhysicalDeviceProperties pfn_vkGetPhysicalDeviceProperties;
extern PFN_vkGetPhysicalDeviceMemoryProperties pfn_vkGetPhysicalDeviceMemoryProperties;
extern PFN_vkGetPhysicalDeviceQueueFamilyProperties pfn_vkGetPhysicalDeviceQueueFamilyProperties;
extern PFN_vkGetPhysicalDeviceSurfaceSupportKHR pfn_vkGetPhysicalDeviceSurfaceSupportKHR;
extern PFN_vkGetPhysicalDeviceSurfaceCapabilitiesKHR pfn_vkGetPhysicalDeviceSurfaceCapabilitiesKHR;
extern PFN_vkGetPhysicalDeviceSurfaceFormatsKHR pfn_vkGetPhysicalDeviceSurfaceFormatsKHR;
extern PFN_vkGetPhysicalDeviceSurfacePresentModesKHR pfn_vkGetPhysicalDeviceSurfacePresentModesKHR;
extern PFN_vkCreateWin32SurfaceKHR pfn_vkCreateWin32SurfaceKHR;
extern PFN_vkDestroySurfaceKHR pfn_vkDestroySurfaceKHR;
extern PFN_vkCreateDebugUtilsMessengerEXT pfn_vkCreateDebugUtilsMessengerEXT;
extern PFN_vkDestroyDebugUtilsMessengerEXT pfn_vkDestroyDebugUtilsMessengerEXT;
extern PFN_vkEnumerateDeviceExtensionProperties pfn_vkEnumerateDeviceExtensionProperties;

// Device-level
extern PFN_vkCreateDevice pfn_vkCreateDevice;
extern PFN_vkDestroyDevice pfn_vkDestroyDevice;
extern PFN_vkGetDeviceQueue pfn_vkGetDeviceQueue;
extern PFN_vkCreateSwapchainKHR pfn_vkCreateSwapchainKHR;
extern PFN_vkDestroySwapchainKHR pfn_vkDestroySwapchainKHR;
extern PFN_vkGetSwapchainImagesKHR pfn_vkGetSwapchainImagesKHR;
extern PFN_vkAcquireNextImageKHR pfn_vkAcquireNextImageKHR;
extern PFN_vkQueuePresentKHR pfn_vkQueuePresentKHR;
extern PFN_vkQueueWaitIdle pfn_vkQueueWaitIdle;
extern PFN_vkDeviceWaitIdle pfn_vkDeviceWaitIdle;
extern PFN_vkCreateCommandPool pfn_vkCreateCommandPool;
extern PFN_vkDestroyCommandPool pfn_vkDestroyCommandPool;
extern PFN_vkAllocateCommandBuffers pfn_vkAllocateCommandBuffers;
extern PFN_vkFreeCommandBuffers pfn_vkFreeCommandBuffers;
extern PFN_vkBeginCommandBuffer pfn_vkBeginCommandBuffer;
extern PFN_vkEndCommandBuffer pfn_vkEndCommandBuffer;
extern PFN_vkCmdBeginRendering pfn_vkCmdBeginRendering;
extern PFN_vkCmdEndRendering pfn_vkCmdEndRendering;
extern PFN_vkCmdBindPipeline pfn_vkCmdBindPipeline;
extern PFN_vkCmdSetViewport pfn_vkCmdSetViewport;
extern PFN_vkCmdSetScissor pfn_vkCmdSetScissor;
extern PFN_vkCmdDraw pfn_vkCmdDraw;
extern PFN_vkCmdBlitImage pfn_vkCmdBlitImage;
extern PFN_vkCmdCopyImageToBuffer pfn_vkCmdCopyImageToBuffer;
extern PFN_vkCmdPipelineBarrier pfn_vkCmdPipelineBarrier;
extern PFN_vkCmdBindVertexBuffers pfn_vkCmdBindVertexBuffers;
extern PFN_vkCmdPushConstants pfn_vkCmdPushConstants;
extern PFN_vkCmdBindDescriptorSets pfn_vkCmdBindDescriptorSets;
extern PFN_vkCreateFence pfn_vkCreateFence;
extern PFN_vkDestroyFence pfn_vkDestroyFence;
extern PFN_vkWaitForFences pfn_vkWaitForFences;
extern PFN_vkResetFences pfn_vkResetFences;
extern PFN_vkCreateSemaphore pfn_vkCreateSemaphore;
extern PFN_vkDestroySemaphore pfn_vkDestroySemaphore;
extern PFN_vkCreateImage pfn_vkCreateImage;
extern PFN_vkDestroyImage pfn_vkDestroyImage;
extern PFN_vkGetImageMemoryRequirements pfn_vkGetImageMemoryRequirements;
extern PFN_vkAllocateMemory pfn_vkAllocateMemory;
extern PFN_vkFreeMemory pfn_vkFreeMemory;
extern PFN_vkBindImageMemory pfn_vkBindImageMemory;
extern PFN_vkCreateImageView pfn_vkCreateImageView;
extern PFN_vkDestroyImageView pfn_vkDestroyImageView;
extern PFN_vkCreateSampler pfn_vkCreateSampler;
extern PFN_vkDestroySampler pfn_vkDestroySampler;
extern PFN_vkCreateBuffer pfn_vkCreateBuffer;
extern PFN_vkDestroyBuffer pfn_vkDestroyBuffer;
extern PFN_vkGetBufferMemoryRequirements pfn_vkGetBufferMemoryRequirements;
extern PFN_vkBindBufferMemory pfn_vkBindBufferMemory;
extern PFN_vkMapMemory pfn_vkMapMemory;
extern PFN_vkUnmapMemory pfn_vkUnmapMemory;
extern PFN_vkCreateShaderModule pfn_vkCreateShaderModule;
extern PFN_vkDestroyShaderModule pfn_vkDestroyShaderModule;
extern PFN_vkCreatePipelineLayout pfn_vkCreatePipelineLayout;
extern PFN_vkDestroyPipelineLayout pfn_vkDestroyPipelineLayout;
extern PFN_vkCreateGraphicsPipelines pfn_vkCreateGraphicsPipelines;
extern PFN_vkDestroyPipeline pfn_vkDestroyPipeline;
extern PFN_vkCreateDescriptorSetLayout pfn_vkCreateDescriptorSetLayout;
extern PFN_vkDestroyDescriptorSetLayout pfn_vkDestroyDescriptorSetLayout;
extern PFN_vkCreateDescriptorPool pfn_vkCreateDescriptorPool;
extern PFN_vkDestroyDescriptorPool pfn_vkDestroyDescriptorPool;
extern PFN_vkAllocateDescriptorSets pfn_vkAllocateDescriptorSets;
extern PFN_vkUpdateDescriptorSets pfn_vkUpdateDescriptorSets;
extern PFN_vkQueueSubmit pfn_vkQueueSubmit;
extern PFN_vkCmdCopyBufferToImage pfn_vkCmdCopyBufferToImage;
extern PFN_vkGetImageSubresourceLayout pfn_vkGetImageSubresourceLayout;
extern PFN_vkFlushMappedMemoryRanges pfn_vkFlushMappedMemoryRanges;
