#pragma once

#ifndef NOMINMAX
#define NOMINMAX
#endif
#ifndef WIN32_LEAN_AND_MEAN
#define WIN32_LEAN_AND_MEAN
#endif
#include <windows.h>

#include <cstdint>
#include <set>
#include <string>
#include <vector>

namespace monix {

struct ProcessInfo {
  std::wstring name;
  int pid = 0;
  int parentPid = 0;
  int sessionId = 0;
  double cpuPct = 0.0;
  std::uint64_t ramBytes = 0;
  double gpuPct = 0.0;
  std::uint64_t createTime100ns = 0;
  std::wstring status;
  std::wstring priority;
  std::wstring processGuid;
};

struct NetworkFlow {
  std::wstring name;
  int activeConnections = 0;
  std::wstring remote;
  std::wstring state;
};

struct Snapshot {
  std::uint64_t snapshotId = 0;
  std::uint64_t collectedAtMonotonicNs = 0;
  std::uint64_t collectedAtWallMs = 0;
  std::wstring host = L"UNKNOWN";
  double cpuPct = 0.0;
  double kernelTimePct = 0.0;
  double userTimePct = 0.0;
  std::uint64_t ramUsedBytes = 0;
  std::uint64_t ramTotalBytes = 0;
  double gpuPct = 0.0;
  int gpuPctValid = 0;
  std::uint64_t diskReadBytesPerSec = 0;
  std::uint64_t diskWriteBytesPerSec = 0;
  std::uint64_t netUpBytesPerSec = 0;
  std::uint64_t netDownBytesPerSec = 0;
  int inboundConnections = 0;
  int outboundConnections = 0;
  int dnsPseudo = 0;
  int latencyMs = -1;
  std::wstring latencySource = L"unavailable";
  double gpuTempC = 0.0;
  bool gpuTempEstimated = false;
  double storageTempC = 0.0;
  bool storageTempEstimated = false;
  int processCount = 0;
  int threadCount = 0;
  int handleCount = 0;
  std::uint64_t pageFileUsedBytes = 0;
  std::uint64_t pageFileTotalBytes = 0;
  int processorQueueLength = 0;
  int contextSwitchesPerSec = 0;
  int systemCallsPerSec = 0;
  int interruptsPerSec = 0;
  std::uint64_t uptimeSeconds = 0;
  std::vector<ProcessInfo> processes;
  std::vector<NetworkFlow> flows;
  char cpuVendor[13] = {};
  char cpuBrand[49] = {};
  uint32_t cpuFamily = 0;
  uint32_t cpuModel = 0;
  uint32_t cpuStepping = 0;
  uint32_t cpuCores = 0;
  uint32_t cpuLogicalCpus = 0;
  uint32_t cpuHtEnabled = 0;
  uint64_t cpuTscPerSec = 0;
  uint32_t cpuMicrocodeRev = 0;
  uint32_t cpuFeaturesEdx = 0;
  uint32_t cpuFeaturesEcx = 0;
  uint32_t cpuExtFeatures = 0;
  double cpuBaseClockMhz = 0.0;
  double estimatedFrequencyMhz = 0.0;
  double kernelUserRatio = 0.0;
  uint64_t cpuTscDelta = 0;
  double ipcEstimate = 0.0;
  std::uint64_t ramAvailBytes = 0;
  std::uint64_t commitUsedBytes = 0;
  std::uint64_t commitLimitBytes = 0;
  std::uint64_t commitPeakBytes = 0;
  std::uint64_t kernelPoolPagedBytes = 0;
  std::uint64_t kernelPoolNonpagedBytes = 0;
  std::uint64_t systemCacheBytes = 0;
  std::uint64_t pageFaultsDelta = 0;
  std::uint64_t hardPageFaultsDelta = 0;
  std::uint64_t standbyListBytes = 0;
  std::uint64_t modifiedListBytes = 0;
  std::uint64_t freeListBytes = 0;
  std::uint64_t zeroListBytes = 0;
  std::uint64_t workingSetTotalBytes = 0;
  double pagefilePctUsed = 0.0;
  double commitPressurePct = 0.0;
  std::uint64_t previousPageFaults = 0;
  std::uint64_t previousHardFaults = 0;
  std::uint64_t totalWorkingSetBytes = 0;
  std::uint64_t diskTotalBytes = 0;
  std::uint64_t diskFreeBytes = 0;
  double diskPctUsed = 0.0;
  double diskQueueLength = 0.0;
  double diskReadLatencyMs = 0.0;
  double diskWriteLatencyMs = 0.0;
  std::uint64_t diskReadIops = 0;
  std::uint64_t diskWriteIops = 0;
  std::uint64_t previousDiskReadBytesPerSec = 0;
  std::uint64_t previousDiskWriteBytesPerSec = 0;
  int smartHealthOk = -1;
  double nvmeTempC = 0.0;
  int nvmeTempValid = 0;
  std::uint64_t previousDiskReadIops = 0;
  std::uint64_t previousDiskWriteIops = 0;
  std::set<std::wstring> netAdapterAddresses;
  std::set<std::wstring> netAdapterGateways;
  std::set<DWORD> netAdapterSpeeds;
  std::set<DWORD> netAdapterOperStatuses;
  std::set<DWORD> netAdapterTypes;
  uint64_t netPrimaryLinkSpeedBps = 0;
  int pingRttMs = -1;
  int dnsResolutionMs = -1;
  int dnsResolutionOk = -1;
  uint64_t tcpRetransmits = 0;
  uint64_t tcpResets = 0;
  uint64_t routeTableHash = 0;
  int proxyEnabled = 0;
  int netAdapterCount = 0;
  int udpConnectionCount = 0;
  std::set<std::wstring> vpnAdapterDescriptions;
  uint64_t totalContextSwitches = 0;
  uint64_t totalInterruptCount = 0;
  uint64_t totalDpcCount = 0;
  uint64_t dpcTimePerSec = 0;
  uint64_t totalIsrCount = 0;
  uint64_t isrTimePerSec = 0;
  int processorCount = 0;
  int suspendedThreadCount = 0;
  int readyThreadCount = 0;
  int waitingThreadCount = 0;
  int realtimeThreadCount = 0;
  int highPriorityThreadCount = 0;
  std::set<int> processorAffinities;
  int threadCountDelta = 0;
  int threadCreationDelta = 0;
  int threadTerminationDelta = 0;

  std::wstring gpuModel;
  std::wstring gpuDriverVersion;
  uint64_t gpuVramTotalBytes = 0;
  uint64_t gpuVramUsedBytes = 0;
  int displayRefreshRateHz = 0;
  int displayWidth = 0;
  int displayHeight = 0;
  int displayBitsPerPel = 0;
  int displayMonitorCount = 0;
  double gpuPowerWatts = 0.0;
  int gpuFanRpm = 0;
  int hdrEnabled = 0;
  int vsyncEnabled = 0;
  int desktopCompositionEnabled = 1;
  double frameTimeMs = 0.0;
  int tdrLevel = 3;
  std::set<std::wstring> displayNames;

  unsigned long long systemTime100ns = 0;
  unsigned long long uptimeMs = 0;
  int bootPhase = 0;
  unsigned long driverCount = 0;
  std::set<std::wstring> driverNames;
  unsigned long long totalHandles = 0;
  unsigned long long totalObjects = 0;
  unsigned long long totalSyscalls = 0;
  unsigned long long ntStatusErrors = 0;
  unsigned long long registryOps = 0;
  unsigned long sessionCount = 0;
  int currentSessionId = 0;
  unsigned long long ioReadBytesDelta = 0;
  unsigned long long ioWriteBytesDelta = 0;
  unsigned long long pnpDeviceCount = 0;
  int timeChangeDetected = 0;

  int selfSignatureValid = -1;
  int selfHashComputed = -1;
  int unsignedDriverCount = 0;
  int suspiciousScriptHosts = 0;
  int uacConsentProcesses = 0;
  int lsassAccessCount = 0;
  int debugPortActive = 0;
  int vmIndicators = 0;
  int hookModulesDetected = 0;
  int peHeaderTamper = 0;
  int scheduledTaskCount = 0;
  std::set<std::wstring> unsignedDriverNames;
  std::set<std::wstring> suspiciousModules;
  std::set<std::wstring> processPaths;
  std::wstring selfExePath;

  int acLineStatus = -1;
  int batteryFlag = 128;
  int batteryLifePercent = -1;
  long long batteryLifeTimeSec = -1;
  int batteryChargeRate = 0;
  int batteryChargeState = 0;
  int batteryChargePercent = -1;
  int batteryWearLevel = -1;
  int batteryCycleCount = -1;
  int batteryTemperature = -1;
  int powerPlanIndex = -1;
  GUID powerPlanGuid = {};
  int powerSaverActive = 0;
  int highPerfActive = 0;
  int balancedActive = 0;
  int modernStandbyActive = -1;
  int sleepStateActive = 0;
  int hibernateActive = 0;
  int cpuPackagePowerCap = -1;
  int systemPowerCap = -1;
  int idlePowerDrawHigh = 0;

  double cpuCoreTempC = 0.0;
  double cpuCoreTempMax = 0.0;
  double motherboardTempC = 0.0;
  double vrmTempC = 0.0;
  double ambientTempC = 0.0;
  double cpuThrottleTempC = 0.0;
  int cpuThrottling = 0;
  int fanCount = 0;
  std::vector<int> fanSpeeds;
  int pumpSpeed = 0;
  int pumpPresent = 0;
  int thermalSensorCount = 0;
  int thermalSensorFailures = 0;
  double thermalTrendC = 0.0;
  int thermalRecoveryCount = 0;
  double thermalHeatSoakIndex = 0.0;
  double coolingCurveSlope = 0.0;

  unsigned long smbiosHash = 0;
  unsigned long acpiHash = 0;
  std::wstring biosVersion;
  std::wstring biosManufacturer;
  int biosMajorVer = 0;
  int biosMinorVer = 0;
  double voltage12V = 0.0;
  double voltage5V = 0.0;
  double voltage33V = 0.0;
  double voltageVcore = 0.0;
  double voltageVram = 0.0;
  int tpmPresent = 0;
  int tpmReady = 0;
  int tpmVersion = 0;
  int cmosBatteryOk = 1;
  int sensorPollFailures = 0;
  int pcieErrors = 0;
  int usbResets = 0;
  int sataResets = 0;
  int thunderboltEvents = 0;
  int ecEvents = 0;
  double boardTempHotspot = 0.0;

  int fsSystem32FileCount = 0;
  int fsSystem32HiddenCount = 0;
  int fsSystem32SystemCount = 0;
  int fsDriversFileCount = 0;
  int fsDriversHiddenCount = 0;
  int fsRecycleBinContentCount = 0;
  int fsProgramFilesCount = 0;
  int fsVolumeDirtyBit = 0;
  std::wstring fsVolumeLabel;
  unsigned long fsVolumeSerial = 0;
  int fsMountPointCount = 0;
  int fsReparsePointCount = 0;
  int fsSparseFileCount = 0;
  int fsAdsWithDataCount = 0;
  int fsIntegrityFailures = 0;
  unsigned long long fsUsnJournalId = 0;
  long long fsLastUsn = 0;
  int fsCorruptionWarnings = 0;
  int fsChkdskPending = 0;

  int regKeyCountRun = 0;
  int regValueCountRun = 0;
  unsigned long regHashRun = 0;
  int regKeyCountRunOnce = 0;
  int regValueCountRunOnce = 0;
  unsigned long regHashRunOnce = 0;
  int regKeyCountShell = 0;
  int regValueCountShell = 0;
  unsigned long regHashShell = 0;
  int regKeyCountPolicies = 0;
  int regValueCountPolicies = 0;
  unsigned long regHashPolicies = 0;
  int regKeyCountServices = 0;
  int regValueCountServices = 0;
  unsigned long regHashServices = 0;
  int regKeyCountDrivers = 0;
  int regValueCountDrivers = 0;
  unsigned long regHashDrivers = 0;
  int regKeyCountFirewall = 0;
  int regValueCountFirewall = 0;
  unsigned long regHashFirewall = 0;
  int regKeyCountUac = 0;
  int regValueCountUac = 0;
  unsigned long regHashUac = 0;
  int regKeyCountTaskSched = 0;
  int regValueCountTaskSched = 0;
  unsigned long regHashTaskSched = 0;
  int regKeyCountCom = 0;
  int regValueCountCom = 0;
  unsigned long regHashCom = 0;
  int regKeyCountTelemetry = 0;
  int regValueCountTelemetry = 0;
  unsigned long regHashTelemetry = 0;
  int regKeyCountAudit = 0;
  int regValueCountAudit = 0;
  unsigned long regHashAudit = 0;
  int regKeyCountEnv = 0;
  int regValueCountEnv = 0;
  unsigned long regHashEnv = 0;
  int regKeyCountPath = 0;
  int regValueCountPath = 0;
  unsigned long regHashPath = 0;
  int regKeyCountAppAssoc = 0;
  int regValueCountAppAssoc = 0;
  unsigned long regHashAppAssoc = 0;
  int regKeyCountShellExt = 0;
  int regValueCountShellExt = 0;
  unsigned long regHashShellExt = 0;
  int regKeyCountDefApp = 0;
  int regValueCountDefApp = 0;
  unsigned long regHashDefApp = 0;
  int regKeyCountFileAssoc = 0;
  int regValueCountFileAssoc = 0;
  unsigned long regHashFileAssoc = 0;
  int regKeyCountConfigFile = 0;
  int regValueCountConfigFile = 0;
  unsigned long regHashConfigFile = 0;
  int startupFolderCount = 0;
  int envVarCount = 0;
  unsigned long regHashEnvPath = 0;

  int audioOutputDeviceCount = 0;
  int audioInputDeviceCount = 0;
  int audioMixerCount = 0;
  DWORD audioMasterVolume = 0;
  int audioMasterMuted = 0;
  DWORD audioMasterVolumeLeft = 0;
  DWORD audioMasterVolumeRight = 0;
  int audioSampleRate = 0;
  int audioBitsPerSample = 0;
  int audioChannels = 0;
  int audioWaveOutOpen = 0;
  int audioWaveInOpen = 0;
  int audioServiceRunning = 1;
  int audioMicMuted = 0;
  int audioSystemMuted = 0;
  int audioHeadphoneJack = -1;
  int audioSpatialization = 0;
  int audioPlaybackActive = 0;
  int audioRecordingActive = 0;
  unsigned long audioDeviceHash = 0;
  unsigned long audioFormatHash = 0;
  int audioLatencyMs = 0;
  int audioCodecEvents = 0;
  int audioDecoderErrors = 0;

  int sehExceptionCount = 0;
  int unhandledExceptionCount = 0;
  int accessViolationCount = 0;
  int heapCorruptionDetected = 0;
  int assertionFailureCount = 0;
  int stackOverflowCount = 0;
  int deadlockRecoveryCount = 0;
  int processRestartCount = 0;
  int moduleReloadCount = 0;
  int uiFreezeDetected = 0;
  int hangDetected = 0;
  int timeoutExceeded = 0;
  int retryStormDetected = 0;
  int backoffEscalation = 0;
  int circuitBreakerOpen = 0;
  int circuitBreakerClose = 0;
  int fallbackModeEntry = 0;
  int fallbackModeExit = 0;
  int configRollbackDetected = 0;
  int safeModeActive = 0;
  int telemetryDropDetected = 0;
  int watchdogResetDetected = 0;
  int serviceRecoveryAction = 0;
  int crashEventsToday = 0;
  int exceptionLogCount = 0;
  unsigned long processHash = 0;
  unsigned long moduleHash = 0;
  int mainThreadResponsive = 1;
  int uiResponsivenessMs = 0;
  int threadHealthOk = 1;
};

}
